name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ec2-user
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        source: "."
        target: "/var/www/html"
